# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bb2849cc7cff2c495914f9fcfc2cd42ebfd7d412055c702ccdf179682f0e81457ea4c9eaf7b548534c146c385dad32d0568de3446ad73f4c8723ca0975eb073

test:
  secret_key_base: ca303950d4bc62b0593d3c8f3f52abfb77355a572d3ec484cc88044f13477db39f8804ccc7268a5a070a3ce9e4d151968a29e8ffad22289fe0a05fad7ccb3c7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
